name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build (PHP v${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0', '8.1']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo
          tools: composer
          coverage: none

      - name: Set up pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.x.x

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          cache: "pnpm"

      - name: Set up Docker Compose
        run: docker-compose --env-file .env.testing up -d

      - name: Create Minio bucket
        run: aws --endpoint-url http://127.0.0.1:9000/ s3 mb s3://local
        env:
          AWS_ACCESS_KEY_ID: laravel
          AWS_SECRET_ACCESS_KEY: password
          AWS_EC2_METADATA_DISABLED: true

      - name: Get Composer cache directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Composer cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: |
          composer install --no-interaction --no-progress
          pnpm install --frozen-lockfile

      - name: Build front-end
        run: pnpm build

      - name: Run tests
        run: |
          php artisan config:clear
          php artisan test

      - name: Destroy Docker Compose
        run: docker-compose --env-file .env.testing down -v
